apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie-rag-config
spec:
  target:
    template:
      data:
        UI_USERNAME: "{{ .username }}"
        UI_PASSWORD: "{{ .password }}"
        MEALIE_EXTERNAL_URL: "http://{{ .mealie_domain }}"
  data:
  - secretKey: mealie_token # pragma: allowlist secret
    remoteRef:
      key: mealie-api-token
  - secretKey: username # pragma: allowlist secret
    remoteRef:
      key: mealie-rag-ui-credentials-username
  - secretKey: password # pragma: allowlist secret
    remoteRef:
      key: mealie-rag-ui-credentials-password
  - secretKey: mealie_domain # pragma: allowlist secret
    remoteRef:
      key: mealie-domain
