apiVersion: apps/v1
kind: Deployment
metadata:
  name: homarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homarr
  template:
    metadata:
      labels:
        app: homarr
    spec:
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: homarr
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          image: ghcr.io/homarr-labs/homarr:v1.50.1
          ports:
            - containerPort: 7575
          envFrom:
            - configMapRef:
                name: homarr-config
          env:
            - name: SECRET_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: homarr-secret
                  key: SECRET_ENCRYPTION_KEY
          volumeMounts:
            - name: homarr-appdata
              mountPath: /appdata
      volumes:
        - name: homarr-appdata
          persistentVolumeClaim:
            claimName: homarr-appdata
