apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homarr-secret
spec:
  refreshInterval: 3h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    name: homarr-secret
  data:
  - secretKey: SECRET_ENCRYPTION_KEY # pragma: allowlist secret
    remoteRef:
      key: homarr-secret-encryption-key
