apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie-db-credentials
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    name: mealie-db-credentials
  data:
  - secretKey: username # pragma: allowlist secret
    remoteRef:
      key: mealie-db-credentials-user
  - secretKey: password # pragma: allowlist secret
    remoteRef:
      key: mealie-db-credentials-password

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-backup-creds
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    name: cnpg-backup-creds
  data:
  - secretKey: storage-account-name # pragma: allowlist secret
    remoteRef:
      key: azure-main-storage-account-name
  - secretKey: storage-account-key # pragma: allowlist secret
    remoteRef:
      key: azure-main-storage-account-key
