apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie-db-credentials
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    name: mealie-db-credentials-2
  data:
  - secretKey: username # pragma: allowlist secret
    remoteRef:
      key: mealie-db-credentials-user
  - secretKey: password # pragma: allowlist secret
    remoteRef:
      key: mealie-db-credentials-password
