apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mealie
resources:
  - ../../base/mealie

patches:
  - path: recovery.yaml
    target:
      kind: Cluster
      name: mealie-db-00
  - path: references_patch.yaml
