apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
spec:
  template:
    spec:
      containers:
        - name: mealie
          env:
            - name: POSTGRES_URL_OVERRIDE
              valueFrom:
                secretKeyRef:
                  name: mealie-db-01-app
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie-db-credentials
spec:
  target:
    name: mealie-db-01-app
    template:
      data:
        pgpass: "mealie-db-01-rw:5432:mealie:mealie:{{ .password }}"
        jdbc-uri: "jdbc:postgresql://mealie-db-01-rw.mealie:5432/mealie?password={{ .password }}&user=mealie"
        uri: "postgresql://mealie:{{ .password }}@mealie-db-01-rw.mealie:5432/mealie"
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: mealie-db-scheduled-backup
spec:
  cluster:
    name: mealie-db-01
