apiVersion: v1
kind: Secret
metadata:
    name: mealie-db-credentials
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:t6kNNkKv,iv:aVuOxXOhYFKb9P07NErRVMaEnQuCF8zq2oOEsKwc0gc=,tag:bs5MBiK9QFiX9/Se7UPUOQ==,type:str]
    password: ENC[AES256_GCM,data:IiUSGmr1jNMQhl2yoF1CBTrnbBwBLomwTBklNAfNVHU=,iv:0dtrr/zqjY4kk7DO10MJ+32nndJZuXBcb2QAZhFiJnw=,tag:gdbkZyZH9MJDj18BWEPzzQ==,type:str]  # pragma: allowlist secret
sops:
    age:
        - recipient: age1y6lznyll67dgphqlj3smfzf006fv400v9c0dm5xt83pp3kvgxg8qagjyf9  # pragma: allowlist secret
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQ2pIeDlmTUVsR2dzZVZo
            dHFhQndSaUI1SjA0RXJHQVRXWEtXUDdDQkZzCkNBcWcrRTlDTmJ3eVFtQ0FkVWJQ
            VlpDOGVIRmhBTjZGTFJiREpKdEVjN2cKLS0tIHJnblVwV1ZqNExORnZsZmViRzRS
            dSt5OHZsVnpZb1BUS1RhYnc1UVBYUVkKKDo0HIn2w7KLT3tRzl5Oi1VxJhmmNXtV
            R2nWcoKaUHcGwoudVOCP5CRPu9XDzfZkhUKZ5Y2xyPDmkC4gskSRTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T19:00:53Z"
    mac: ENC[AES256_GCM,data:wcqaSM+SHPqSwXK3c0NZsuE5xSgQzmE80YRzfXFBh20D+DJS2JlVkbAtHbWqDhDxiimExOddjh115tsW0jqLPwhtCPZ9rSRBvMVcKntWd2fT3Zk9+Odpg0X0W5UykdaibivE1kM6KjMWZB3p5T/bllRFEzeN9dEEb7hA2fEltyA=,iv:u0dRT+NULTmJDxfjpRKCmImFEIwkBgNZp/X5x2Vf8Ts=,tag:bBD3EGvbWP8uRkAPfUL/cQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
