apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-db-credentials
spec:
  refreshInterval: 3h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    name: litellm-db-00-app
    creationPolicy: Merge
    deletionPolicy: Merge
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        password: "{{ .password }}"
        pgpass: "litellm-db-00-rw:5432:litellm:litellm:{{ .password }}"
        jdbc-uri: "jdbc:postgresql://litellm-db-00-rw.litellm:5432/litellm?password={{ .password }}&user=litellm"
        uri: "postgresql://litellm:{{ .password }}@litellm-db-00-rw.litellm:5432/litellm"
  data:
  - secretKey: password # pragma: allowlist secret
    remoteRef:
      key: litellm-db-credentials-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-db-objectstore
spec:
  refreshInterval: 3h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    name: cnpg-backup-creds
  data:
  - secretKey: storage-account-name # pragma: allowlist secret
    remoteRef:
      key: azure-main-storage-account-name
  - secretKey: storage-account-key # pragma: allowlist secret
    remoteRef:
      key: azure-main-storage-account-key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-secrets
spec:
  refreshInterval: 3h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    name: litellm-secrets
  data:
  - secretKey: LITELLM_SALT_KEY # pragma: allowlist secret
    remoteRef:
      key: litellm-salt-key
  - secretKey: LITELLM_MASTER_KEY # pragma: allowlist secret
    remoteRef:
      key: litellm-master-key
