apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: health-db-grafana
spec:
  refreshInterval: 3h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    name: health-db-grafana
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
      data:
        username: health_grafana
        password: "{{ .password }}"
  data:
    - secretKey: password # pragma: allowlist secret
      remoteRef:
        key: health-db-grafana-password
