apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velero-backup-creds
spec:
  refreshInterval: 3h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    name: velero-backup-creds
    template:
      data:
        cloud: |
          AZURE_STORAGE_ACCOUNT_ACCESS_KEY: "{{ .AZURE_STORAGE_ACCOUNT_KEY }}"
  data:
  # - secretKey: AZURE_STORAGE_ACCOUNT_ID
  #   remoteRef:
  #     key: azure-main-storage-account-name
  - secretKey: AZURE_STORAGE_ACCOUNT_KEY # pragma: allowlist secret
    remoteRef:
      key: azure-main-storage-account-key
