apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
spec:
  dependsOn:
    - name: external-secrets
      namespace: external-secrets
  interval: 12h
  chart:
    spec:
      chart: velero
      version: 11.3.2
      sourceRef:
        kind: HelmRepository
        name: velero
      interval: 12h
  values:
    credentials:
      existingSecret: velero-backup-creds  # pragma: allowlist secret
    snapshotsEnabled: false
    deployNodeAgent: true
    configuration:
      logFormat: json
      backupStorageLocation:
        - name: default
          provider: velero.io/azure
          bucket: velero-backups
          config:
            storageAccount: "${STORAGE_ACCOUNT_NAME}"
            storageAccountURI: "https://${STORAGE_ACCOUNT_NAME}.blob.core.windows.net"
            storageAccountKeyEnvVar: "AZURE_STORAGE_ACCOUNT_ACCESS_KEY"  # pragma: allowlist secret
    initContainers:
      - name: velero-plugin-for-microsoft-azure
        image: velero/velero-plugin-for-microsoft-azure:v1.14.2
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
