apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: forgejo
resources:
  - ../../base/forgejo
  - external-secret.yaml
  - ingress.yaml

patches:
  - path: velero_backup_patch.yaml
