apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velero-repo-credentials
spec:
  refreshInterval: 3h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    name: velero-repo-credentials
    creationPolicy: Merge
    deletionPolicy: Merge
    template:
      data:
        repository-password: "{{ .repository_password }}"
  data:
  - secretKey: repository_password # pragma: allowlist secret
    remoteRef:
      key: velero-repo-credentials-password
