apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily
spec:
  schedule: 0 5 * * *
  template:
    excludedNamespaces:
    - flux-system
    - kube-system
    includedResources:
    - deployments
    - pods
    - pvc
    - pv
    ttl: 480h # 20 days
