apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily
spec:
  schedule: 0 5 * * *
  template:
    excludedNamespaces:
    - flux-system
    - kube-system
    - monitoring
    - velero
    - cnpg-system
    - cert-manager
    - external-secrets
    includedResources:
    - deployments
    - pods
    - pvc
    - pv
    ttl: 480h # 20 days
