apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie-db-credentials
spec:
  refreshInterval: 5m # TODO: revert me
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    name: mealie-db-00-app
    creationPolicy: Merge
    deletionPolicy: Merge
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        password: "{{ .password }}"
        # pgpass: "mealie-db-00-rw:5432:app:app:{{ .password }}"
        # jdbc-uri: "jdbc:postgresql://mealie-db-00-rw.default:5432/app?password={{ .password }}&user=app"
        # uri: "postgresql://app:{{ .password }}@mealie-db-00-rw.default:5432/app"
  data:
  - secretKey: password # pragma: allowlist secret
    remoteRef:
      key: mealie-db-credentials-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-backup-creds
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    name: cnpg-backup-creds
  data:
  - secretKey: storage-account-name # pragma: allowlist secret
    remoteRef:
      key: azure-main-storage-account-name
  - secretKey: storage-account-key # pragma: allowlist secret
    remoteRef:
      key: azure-main-storage-account-key
