apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - external_secret.yaml
  - namespace.yaml
  - objectstore.yaml
  - persistent-volume-claim.yaml
  - postgresql.yaml
  - scheduled-backup.yaml
  - service.yaml

configMapGenerator:
  - name: mealie-config
    literals:
      - ALLOW_SIGNUP=false
      - PU_ID=1000
      - PG_ID=1000
      - TZ=Europe/London
      - DB_ENGINE=postgres
