apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: mealie-db-objectstore
spec:
  configuration:
    destinationPath: "https://${STORAGE_ACCOUNT_NAME}.blob.core.windows.net/cnpg-backups/mealie"
    azureCredentials:
      storageAccount:
        name: cnpg-backup-creds
        key: storage-account-name
      storageSasToken:
        name: cnpg-backup-creds
        key: storage-account-key
    wal:
      compression: gzip
  retentionPolicy: "14d"
