apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mealie-db
spec:
  instances: 3

  # bootstrap:
  #   initdb:
  #     database: mealie
  #     owner: mealie
  #     secret:
  #       name: mealie-db-credentials

  bootstrap:
    recovery:
      source: mealie-db-backup
      database: mealie
      owner: mealie
      secret:
        name: mealie-db-credentials

  externalClusters:
    - name: mealie-db-backup
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: mealie-db-objectstore
          serverName: mealie-db

  storage:
    size: 1Gi # TODO: confirm this size

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: mealie-db-objectstore
