apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: akri
spec:
  interval: 12h
  chart:
    spec:
      chart: akri
      version: "0.x"
      sourceRef:
        kind: HelmRepository
        name: akri
        namespace: akri
      interval: 12h
  # https://github.com/project-akri/akri/blob/main/deployment/helm/values.yaml
