apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - namespace.yaml
  - persistent-volume-claim.yaml
  - service.yaml

configMapGenerator:
  - name: n8n
    literals:
      - N8N_PROTOCOL=http
      - N8N_PORT=5678
      - TZ=Europe/London
