apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-secrets
spec:
  refreshInterval: 3h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    name: litellm-secrets
  data:
  - secretKey: LITELLM_SALT_KEY # pragma: allowlist secret
    remoteRef:
      key: litellm-salt-key
  - secretKey: LITELLM_MASTER_KEY # pragma: allowlist secret
    remoteRef:
      key: litellm-master-key
  - secretKey: LANGFUSE_SECRET_KEY # pragma: allowlist secret
    remoteRef:
      key: litellm-langfuse-secret-key
  - secretKey: LANGFUSE_PUBLIC_KEY # pragma: allowlist secret
    remoteRef:
      key: litellm-langfuse-public-key
  - secretKey: LANGFUSE_HOST # pragma: allowlist secret
    remoteRef:
      key: litellm-langfuse-host
