apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: cloudflared
  template:
    metadata:
      labels:
        pod: cloudflared
    spec:
      # securityContext:
      #   sysctls:
      #   # Allows ICMP traffic (ping, traceroute) to resources behind cloudflared.
      #     - name: net.ipv4.ping_group_range
      #       value: "65532 65532"
      containers:
        - image: cloudflare/cloudflared:latest
          name: cloudflared
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflared-tunnel-token
                  key: token
          command:
            - cloudflared
            - tunnel
            - --config
            - /etc/cloudflared/config/config.yaml
            - run
          livenessProbe:
            httpGet:
              # Cloudflared has a /ready endpoint which returns 200 if and only if
              # it has an active connection to Cloudflare's network.
              path: /ready
              port: 2000
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
          - name: config
            mountPath: /etc/cloudflared/config
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: cloudflared
            items:
            - key: config.yaml
              path: config.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
data:
  config.yaml: |
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
    - hostname: links.andlogreg.work
      service: http://littlelink:3000
    - hostname: links.andlogreg.work
      service: hello_world
    # This rule matches any traffic which didn't match a previous rule, and responds with HTTP 404.
    - service: http_status:404
