apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-tunnel-token
spec:
  refreshInterval: 3h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    name: cloudflared-tunnel-token
  data:
  - secretKey: token # pragma: allowlist secret
    remoteRef:
      key: littlelink-cloudflared-tunnel-token
