apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gpu-operator
spec:
  interval: 12h
  chart:
    spec:
      chart: gpu-operator
      version: v25.10.1
      sourceRef:
        kind: HelmRepository
        name: gpu-operator
      interval: 12h
  values:
    toolkit:
      env:
        - name: CONTAINERD_SOCKET
          value: /run/k3s/containerd/containerd.sock
    dcgmExporter:
      serviceMonitor:
        enabled: true
        interval: 15s
        honorLabels: true
    # driver:
    #   # kernel module configuration for NVIDIA driver
    #   kernelModuleConfig:
    #     name: "kernel-module-params"
  #   devicePlugin:
  #     config:
  #       name: time-slicing-config
  #       default: any
