general_settings:
  proxy_batch_write_at: 60 # Batch write spend updates every 60s
  database_connection_pool_limit: 10

litellm_settings:
  json_logs: true

router_settings:
  enable_pre_call_checks: true
