apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vllm
resources:
  - ../../base/vllm/cpu

configMapGenerator:
  - name: vllm-config
    literals:
      - MODEL_NAME=meta-llama/Llama-3.2-1B-Instruct
      - VLLM_ARGS=""
      - VLLM_TARGET_DEVICE=cpu
      - VLLM_LOGGING_LEVEL=DEBUG

patches:
  - target:
      kind: Deployment
      name: vllm
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/envFrom
        value:
          - configMapRef:
              name: vllm-config
