apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: open-webui
resources:
  - ../../base/open-webui
  - ingress.yaml

configMapGenerator:
  - name: open-webui-config
    behavior: merge
    literals:
      - OPENAI_API_BASE_URL=http://vllm-inference.vllm.svc.cluster.local:8000/v1
      - OPENAI_API_KEY=O3wu^TV$D # pragma: allowlist secret
