apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-servers
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "Mealie DB",
          "Group": "Servers",
          "Host": "mealie-db-00-rw.mealie",
          "Port": 5432,
          "MaintenanceDB": "mealie",
          "Username": "mealie",
          "SSLMode": "prefer"
        }
      }
    }
