apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie-rag-config
spec:
  refreshInterval: 3h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    name: mealie-rag-config
    template:
      data:
        MEALIE_TOKEN: "{{ .mealie_token }}"
  data:
  - secretKey: mealie_token # pragma: allowlist secret
    remoteRef:
      key: mealie-api-token
