apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie-rag-config
spec:
  refreshInterval: 3h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    name: mealie-rag-config
    template:
      data:
        MEALIE_TOKEN: "{{ .mealie_token }}"
        API_KEY: "{{ .api_key }}"
  data:
    - secretKey: mealie_token # pragma: allowlist secret
      remoteRef:
        key: mealie-api-token
    - secretKey: api_key # pragma: allowlist secret
      remoteRef:
        key: mealie-rag-api-key
