apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cronjob.yaml
  - deployment.yaml
  - external-secret.yaml
  - service.yaml

configMapGenerator:
  - name: mealie-rag-config
    literals:
      - DELETE_COLLECTION_IF_EXISTS=true
      - SEARCH_STRATEGY=multiquery
      - LOG_LEVEL=debug

images:
  - name: ghcr.io/andlogreg/mealierag
    newTag: mealierag-v0.5.1
