apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tunnel-credentials
spec:
  refreshInterval: 3h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    name: cloudflared-tunnel
    template:
      data:
        config.yaml: |
          tunnel: {{ .tunne-id }}
          metrics: 0.0.0.0:2000
          no-autoupdate: true
          credentials-file: /etc/cloudflared/creds/credentials.json
          ingress:
            - hostname: {{ .mealie-domain }}
              service: http://mealie.mealie.svc.cluster.local:80
            - service: http_status:404 # Catch-all
        token: "{{ .tunnel-secret }}"
  data:
  - secretKey: tunnel-secret # pragma: allowlist secret
    remoteRef:
      key: cloudflared-tunnel-secret
  - secretKey: tunnel-id # pragma: allowlist secret
    remoteRef:
      key: cloudflared-tunnel-id
  - secretKey: mealie-domain # pragma: allowlist secret
    remoteRef:
      key: mealie-domain
