apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie-openai-secret
spec:
  refreshInterval: 3h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    name: mealie-openai-secret
  data:
  - secretKey: OPENAI_API_KEY # pragma: allowlist secret
    remoteRef:
      key: openai-api-key
  - secretKey: OPENAI_BASE_URL # pragma: allowlist secret
    remoteRef:
      key: openai-base-url
