apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - namespace.yaml
  - persistent-volume-claim.yaml
  - service.yaml

configMapGenerator:
  - name: forgejo-config
    literals:
      - FORGEJO____APP_NAME="Andlogreg - Forgejo"
      - FORGEJO____APP_SLOGAN="Your code, your rules"
      - FORGEJO__server__PROTOCOL=https
      - FORGEJO__server__DOMAIN=forgejo.andlogreg.work
      - FORGEJO__server__ROOT_URL=https://forgejo.andlogreg.work
      - FORGEJO__server__SSH_LISTEN_PORT=2222
      - FORGEJO__server__SSH_PORT=2222
      - FORGEJO__database__DB_TYPE=sqlite3
      - FORGEJO__actions__ENABLED=false
