apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie-rag-ui-credentials
spec:
  refreshInterval: 3h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    name: mealie-rag-config
    creationPolicy: Merge
    deletionPolicy: Merge
    template:
      data:
        UI_USERNAME: "{{ .username }}"
        UI_PASSWORD: "{{ .password }}"
  data:
  - secretKey: username # pragma: allowlist secret
    remoteRef:
      key: mealie-rag-ui-credentials-username
  - secretKey: password # pragma: allowlist secret
    remoteRef:
      key: mealie-rag-ui-credentials-password
