apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie-rag-config
spec:
  target:
    template:
      data:
        UI_USERNAME: "{{ .username }}"
        UI_PASSWORD: "{{ .password }}"
        LLM_API_KEY: "{{ .llm_api_key }}"
        TRACING_PUBLIC_KEY: "{{ .tracing_public_key }}"
        TRACING_SECRET_KEY: "{{ .tracing_secret_key }}"
  data:
  - secretKey: mealie_token # pragma: allowlist secret
    remoteRef:
      key: mealie-api-token
  - secretKey: username # pragma: allowlist secret
    remoteRef:
      key: mealie-rag-ui-credentials-username
  - secretKey: password # pragma: allowlist secret
    remoteRef:
      key: mealie-rag-ui-credentials-password
  - secretKey: llm_api_key # pragma: allowlist secret
    remoteRef:
      key: mealie-rag-llm-api-key
  - secretKey: tracing_public_key # pragma: allowlist secret
    remoteRef:
      key: mealie-rag-tracing-public-key
  - secretKey: tracing_secret_key # pragma: allowlist secret
    remoteRef:
      key: mealie-rag-tracing-secret-key
