apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mealie-rag
resources:
  - ../../base/mealie-rag
  - ingress.yaml

patches:
  - path: external-secret.yaml
#   - target:
#       kind: Deployment
#       name: mealie-rag
#     patch: |
#       - op: add
#         path: /spec/template/spec/containers/0/imagePullPolicy
#         value: Always

# images:
#   - name: ghcr.io/andlogreg/mealierag
#     newTag: feat-structured_outs

configMapGenerator:
  - name: mealie-rag-config
    behavior: merge
    literals:
      - MEALIE_EXTERNAL_URL=http://mealie.staging.andlogreg.work
      - LLM_MODEL=mealie-rag-llm-staging
      - EMBEDDING_MODEL=mealie-rag-embedding-staging
      - TRACING_ENVIRONMENT=staging
