apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily
spec:
  schedule: 0 5 * * *
  template:
    includedNamespaces:
    - forgejo
    - homarr
    - linkding
    - mealie
    includedResources:
    - deployments
    - pods
    - pvc
    - pv
    ttl: 480h # 20 days
