apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  interval: 12h
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "80.x"
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: monitoring
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
    ignore:
      # Ignore "validated" annotation which is not inserted during install
      - paths: ["/metadata/annotations/prometheus-operator-validated"]
        target:
          kind: PrometheusRule
  # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
  values:
    grafana:
      adminPassword: whoami # pragma: allowlist secret
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - grafana.andlogreg.work
      additionalDataSources:
        - name: Loki
          type: loki
          url: http://loki.monitoring.svc.cluster.local:3100
          access: proxy
          isDefault: false
    prometheus:
      prometheusSpec:
        # Prometheus find all ServiceMonitors regardless of labels
        serviceMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelector: {}
        # Prometheus find ServiceMonitors in all namespaces
        serviceMonitorNamespaceSelector: {}
    kubeScheduler:
      enabled: false
    kubeControllerManager:
      enabled: false
    kubeEtcd:
      enabled: false
    defaultRules:
      rules:
        etcd: false
        kubeSchedulerAlerting: false
        kubeSchedulerRecording: false
        kubeControllerManager: false
