apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - namespace.yaml
  - persistent-volume-claim.yaml
  - service.yaml

configMapGenerator:
  - name: open-webui-config
    literals:
      - OLLAMA_BASE_URL=http://ollama.ollama.svc.cluster.local:11434
