apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hf-token
spec:
  refreshInterval: 3h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    name: hf-token
  data:
  - secretKey: token # pragma: allowlist secret
    remoteRef:
      key: huggingface-token
