apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkding-credentials
spec:
  refreshInterval: 3h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    name: linkding-credentials
    template:
      data:
        LD_SUPERUSER_PASSWORD: "{{ .password }}"
        LD_SUPERUSER_NAME: "{{ .username }}"
  data:
  - secretKey: password # pragma: allowlist secret
    remoteRef:
      key: linkding-credentials-password
  - secretKey: username # pragma: allowlist secret
    remoteRef:
      key: linkding-credentials-username
