apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - external-secret.yaml
  - namespace.yaml
  - persistent-volume-claim.yaml
  - service.yaml

configMapGenerator:
  - name: linkding-config
    literals:
      - LD_DB_ENGINE=sqlite
