apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-secret-store
spec:
  provider:
    azurekv:
      authType: ServicePrincipal
      vaultUrl: "${VAULT_URL}"
      tenantId: "${AZURE_TENANT_ID}"
      authSecretRef:
        clientId:
          name: eso-sp-credentials
          key: client-id
        clientSecret:
          name: eso-sp-credentials
          key: client-secret
