apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
spec:
  schedule: '@daily'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              image: renovate/renovate:42.71.0
              args:
                - andlogreg/homelab-gitops
              envFrom:
                - secretRef:
                    name: renovate
                - configMapRef:
                    name: renovate
          restartPolicy: Never
