apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate
spec:
  refreshInterval: 3h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    name: renovate
  data:
  - secretKey: RENOVATE_TOKEN # pragma: allowlist secret
    remoteRef:
      key: renovate-token
